"use client";

import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";

type Props = {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: Date;
};

const DownloadSummaryButton = ({
  createdAt,
  fileName,
  summaryText,
  title,
}: Props) => {
  const handleDownloadSummary = () => {
    const summaryContent = `#${title}
    Generated Summary
    Generated on: ${new Date(createdAt).toLocaleDateString()}
    
    ${summaryText}

    Original File: ${fileName}
    Generated by Sommaire`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-zA-Z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      size={"sm"}
      onClick={handleDownloadSummary}
      className="h-8 border border-rose-200 bg-rose-100 px-3 text-rose-600 hover:bg-rose-200 hover:text-rose-700"
    >
      <Download />
      <span>Download</span>
    </Button>
  );
};

export default DownloadSummaryButton;
